### PR TITLE
Improve getting started for users

### PR DESCRIPTION
**Pull request by Ibrahim-Halil-Kuray**
# Pull Request Details 

Issue #330 

## Description

The handbook button now redirects the to documentation/handbook instead of gdoc link.
Images categorized, their names improved, they categorized and the document quality improved.

### CODE REVIEW

**Review by loleg — APPROVED** [review]
Looks good! Did you test this already on your local machine?

**Comment by Ibrahim-Halil-Kuray** [comment]
Yes, it works.

**Comment by Ibrahim-Halil-Kuray** [comment]
Screenshot 2023-09-05 at 13 37 33

**Comment by Ibrahim-Halil-Kuray** [comment]
Screenshot 2023-09-05 at 13 38 51

**Comment by loleg** [comment]
We can test in stage. I don't expect major issues and it's also more relevant than the local dev environment.

**Pull request merged**
