### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sprotest**
# Pull Request Details

## Related Issue
[Issue template](issue_template.md)

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[coding style](coding_style.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sprotest** [comment]
test commit

**Comment by loleg** [comment]
it works :)

**Comment by tafonina** [comment]
testing

**Comment by tafonina** [comment]
close testing pr

**Pull request closed without merging**
